# Generated by Django 3.2.8 on 2022-03-24 02:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=140, verbose_name='テキスト')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 2, 10, 23, 271853, tzinfo=utc), verbose_name='投稿日時')),
            ],
        ),
    ]
