# Generated by Django 3.2.8 on 2022-04-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_likemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='LikeModel',
            old_name='article',
            new_name='tweet'
        )
    ]
